Repository tryber/sd-09-project-frontend-online-store, pull requests merged in 2021-03, with the labels that each got.

#29 requisito 1
  src/services/api.js
Labels: code review

#19 [Grupo 04] - Módulo de Acesso a API
  src/services/api.js
Labels: code review

#39 [GRUPO 28] - REQUISITO 1
  package-lock.json
  src/services/api.js
Labels: code review

#43 g13-requisito-2
  src/App.js
Labels: code review

#23 [GRUPO6][REQUISITO1] Implemente o módulo de acesso à api do Mercado Livre
  src/App.js
  src/services/api.js
Labels: code review

#37 [feat] [req 2] Página Inicial
  package-lock.json
  src/App.js
  src/pages/ProductList.js
Labels: code review

#52 [GRUPO 28] - Requisito 2
  src/App.js
  src/components/ProductList.js
Labels: code review

#55 [group-14][Req.01: implement api.js functions]
  package-lock.json
  src/App.js
  src/services/api.js
Labels: code review

#57 Questao2
  README.md
  package-lock.json
  src/App.js
  src/services/List.js
  src/services/Search.js
Labels: code review

#71 [GRUPO6][REQUISITO2] Crie uma página de listagem de produtos vazia
  src/App.js
  src/components/ProductList.js
  src/components/Search.js
  src/services/api.js
Labels: code review

#80 g13-requisito 3
  src/App.js
  src/pages/Home.js
  src/pages/ShoppingCart.js
Labels: code review

#25 [FEAT] [1,2,3]
  package-lock.json
  public/index.html
  src/App.js
  src/components/Carrinho.js
  src/components/Home.js
  src/services/api.js
Labels: code review

#85 g13 list categories component
  src/App.css
  src/components/Categories/index.js
  src/components/Categories/styles.css
  src/pages/Home.js
Labels: code review

#15 iniciando o projeto
  package-lock.json
  src/App.js
  src/components/CategoriesList.jsx
  src/components/Home.jsx
  src/components/ShoppingCart.jsx
  src/services/api.js
Labels: code review

#70 [Grupo 23][No Master Store] - Exercício 3
  src/App.js
  src/pages/Cart.js
Labels: code review

#90 [Grupo 23] Ex.1 - Implementar o módulo de acesso à api do Mercado Livre
  src/services/api.js
Labels: code review

#110 [Grupo 4] - Feat/Listagem de produtos
  src/components/Product.js
  src/components/SearchBar.js
Labels: code review

#68 Requisito 2 - Crie uma página de listagem de produtos vazia
  src/App.js
  src/components/Header.jsx
Labels: code review

#127 g13-requisito-5
  src/Components/ProductCard.js
  src/pages/Home.js
Labels: code review

#139 g13 requisito 7
  src/App.js
  src/Components/Categories/index.js
  src/Components/Categories/styles.css
  src/Components/ProductCard.js
  src/pages/Home.js
  src/pages/ProductDetails.js
Labels: code review

#86 [FEAT][REQUIREMENT 03][SHOPPING CART BUTTON]
  src/App.js
  src/pages/ProductList.js
  src/pages/ShoppingCart.js
Labels: code review

#153 [Grupo 04] - Feat / Requisito-06
  src/components/CategoriesList.js
  src/components/SearchBar.js
Labels: code review

#160 [Grupo 04] - Feat/Requisito07
  src/App.js
  src/components/Product.js
  src/components/SearchBar.js
  src/components/ShoppingCart.js
  src/components/ShoppingCartButton.js
  src/index.js
  src/pages/Details.js
Labels: code review

#155 [Grupo 10] [Requisito 05]
  src/App.js
  src/Components/Card.css
  src/Components/Card.js
  src/Components/CardList.js
  src/Pages/Search.jsx
  src/Search.jsx
  src/services/api.js
Labels: code review

#170 [Grupo 20] Requisito 2 para análise
  src/App.js
  src/pages/home.js
Labels: code review

#180 g13-fix-get-categoories
  src/Components/Categories/Categories.css
  src/Components/Categories/Categories.js
  src/pages/Home.js
Labels: code review

#186 Main group 23 feat/requisito5
  src/App.js
  src/components/Card.js
  src/pages/LandingPage.js
Labels: code review

#198 [No Master, No Store] Ex.4 - Liste as categorias de produtos disponíveis via API na página …
  src/pages/ListCategories.js
Labels: code review

#146 [GROUP 5][FEAT][SHOPPING CART PAGE]
  src/App.js
  src/ProductList.js
  src/components/shopping_cart/ButtonCart.js
  src/components/shopping_cart/ShoppingCart.css
  src/components/shopping_cart/ShoppingCart.js
  src/components/shopping_cart/logo_arrow_back.svg
  src/components/shopping_cart/logo_shop_cart.svg
Labels: code review

#201 [No Master, No Store] Ex.4 - Refatoração
  src/App.js
  src/pages/ListCategories.js
Labels: code review

#189 [Grupo 10][Requisito 04]
  src/App.js
  src/Components/ListCategories.js
  src/Images/botaoCarrinho.jpg
  src/Images/carrinhovazio.jpg
  src/Pages/Carrinho.js
  src/Pages/Search.css
  src/Pages/Search.jsx
  src/services/api.js
Labels: code review

#132 GROUP 35 - [feat] (CategoriesList): Adiciona requisito 4
  src/components/CategoriesList.css
  src/components/CategoriesList.js
  src/components/CategoryInput.js
  src/pages/ProductList.css
  src/pages/ProductList.js
Labels: code review

#243 requisito 8
  src/App.css
  src/Components/CardShoppingCart/CardShoppingCart.css
  src/Components/CardShoppingCart/CardShoppingCart.js
  src/Components/Categories/Categories.js
  src/Components/ProductCard/ProductCard.css
  src/Components/ProductCard/ProductCard.js
  src/pages/ShoppingCart.js
  src/services/Data.js
Labels: code review

#228 [FEAT] [4, 5, 6]
  package-lock.json
  src/App.js
  src/components/Carrinho.js
  src/components/Categories.jsx
  src/components/Home.js
  src/components/SearchCard.jsx
  src/index.css
Labels: code review

#221 [Grupo 10][Requisito 06]
  src/Components/ListCategories.js
  src/Pages/Search.jsx
Labels: code review

#249 g13-requisito 9
  src/pages/ProductDetails.js
Labels: code review

#251 add fontawesome
  package-lock.json
  package.json
  src/Components/ProductCard/ProductCard.js
Labels: code review

#61 [FEAT][SearchField]
  package-lock.json
  src/App.js
  src/Components/SearchField.jsx
Labels: code review

#244 [Group-20] [Req-04]
  public/images/icons8-empty-box-100.png
  public/images/icons8-undo-52.png
  src/App.js
  src/pages/ShoppingCart.js
  src/pages/home.js
  src/styles/pages/Home.css
  src/styles/pages/ShoppingCart.css
Labels: code review

#223 [Group-20][Req-3]
  public/images/icons8-empty-box-100.png
  public/images/icons8-undo-52.png
  src/App.js
  src/pages/ShoppingCart.js
  src/pages/home.js
  src/styles/pages/Home.css
  src/styles/pages/ShoppingCart.css
Labels: code review

#197 [GROUP 5][FEATURE] Requisito 4
  src/App.js
  src/components/AsideCategoriesList.css
  src/components/AsideCategoriesList.jsx
Labels: code review

#256 g13-requisito-10
  src/Components/CardShoppingCart/CardShoppingCart.js
  src/Components/ProductCard/ProductCard.js
Labels: code review

#241 [Grupo 28] - Requisito 3
  src/App.js
  src/components/CartButton.js
  src/components/ProductList.js
Labels: code review

#234 [Grupo 28] - Requisito 5
  src/App.css
  src/components/ProductItem.jsx
  src/components/ProductList.js
  src/services/api.js
Labels: code review

#275 [Grupo 23] Select a category and show only products in that category
  src/App.js
  src/pages/LandingPage.js
  src/pages/ListCategories.js
Labels: code review

#268 Main group 35 req3 cartshop
  package-lock.json
  package.json
  src/App.js
  src/components/CartIcon.jsx
  src/components/SearchBar.js
  src/pages/CartShop.jsx
  src/pages/ProductList.js
Labels: code review

#280 g13-requisito-14
  src/Components/CardShoppingCart/CardShoppingCart.js
  src/Components/ProductCard/ProductCard.js
Labels: code review

#297 [No Master, No Store] feat do exercicio 7 - detalhes do produto
  src/App.js
  src/components/Card.js
  src/pages/LandingPage.js
  src/pages/ProductDetais.js
Labels: code review

#301 g13 requisito 15
  src/Components/ProductCard/ProductCard.js
Labels: code review

#305 G13 requisito 11
  src/Components/AvaliationForm/AvaliationForm.css
  src/Components/AvaliationForm/AvaliationForm.js
  src/Components/ButtonsCardDetails/ButtonsCardDetails.css
  src/Components/ButtonsCardDetails/ButtonsCardDetails.js
  src/pages/ProductDetails.css
  src/pages/ProductDetails.js
Labels: code review

#314 [No Master No Store] feat ex 8 add itens no carrinho
  src/components/Card.js
  src/pages/Cart.js
  src/pages/LandingPage.js
Labels: code review

#325 [No Master No Store] feat ex 9 add itens no carrinho
  src/pages/ProductDetais.js
Labels: code review

#307 [Grupo 28] - Requisito 4
  package-lock.json
  src/components/CategoryList.js
  src/components/ProductList.js
Labels: code review

#295 [Grupo 04] - Feat/ Requisito 15
  src/components/Product.js
  src/pages/Details.js
Labels: code review

#304 Group 35 - feat(ProductList): Adiciona requisito 6
  src/App.js
  src/components/CartIcon.jsx
  src/components/CategoriesList.js
  src/components/CategoryInput.js
  src/components/NoSearchText.js
  src/components/SearchStatusMsg.js
  src/pages/ProductList.js
Labels: code review

#303 [GROUP 5][FEAT][LIST PRODUCTS SEARCHED]
  src/App.js
  src/ProductList.js
  src/components/AsideCategoriesList.jsx
  src/components/ProductCard.js
  src/components/search_logo.svg
Labels: developing

#356 [No Master No Store] - Requisito 11 avaliações de produtos
  src/components/EvaluationForm.js
  src/components/Evaluations.js
  src/pages/ProductDetais.js
Labels: code review

#369 [grupo 19] mergeando req7 e req8
  src/components/Product.js
  src/components/Products.js
Labels: code review

#385 Added Req9
  src/components/Product.js
  src/components/ProductDetails.js
  src/components/Products.js
  src/pages/Details.js
Labels: code review

#382 [FEAT][Requisitos 7-8-9]
  README.md
  src/App.js
  src/components/Carrinho.js
  src/components/Detalhes.jsx
  src/components/Home.js
  src/components/ItemsCart.jsx
  src/components/SearchCard.jsx
Labels: code review

#403 g13-projeto 100%
  src/Components/CounterCart/CounterCart.js
  src/Components/ProductCard/ProductCard.js
  src/Components/ProductDetailCard/ProductDetails.css
  src/Components/ProductDetailCard/ProductDetailscard.js
  src/pages/Home.js
  src/pages/ProductDetails.js
Labels: code review

#418 Category search feature
  src/components/CartButton.js
  src/components/ProductCard.js
  src/pages/CardProduct.jsx
  src/pages/ProductList.js
Labels: code review

#426 [FEAT][REQUIREMENT 07][PRODUCT DETAILS PAGE]
  src/App.js
  src/components/ProductCard.js
  src/pages/ProductDetails.js
  src/services/api.js
Labels: code review

#424 adicionado requisito 10
  src/components/Product.js
  src/pages/ShoppingCart.js
Labels: code review

#423 Group-16/requisito 7, 8, 9
  src/App.js
  src/components/DetailEvaluation.jsx
  src/components/ProductCard.jsx
  src/components/ShoppingCartButton.jsx
  src/pages/ProductDetails.jsx
  src/pages/ProductList.jsx
  src/pages/ShoppingCart.jsx
Labels: code review

#425 [Grupo 10][Requisito 13]
  src/App.js
  src/Components/Card.js
  src/Components/CardShoppingCart.js
  src/Components/CardShoppingCartList.js
  src/Pages/Checkout.js
  src/Pages/Pages.css
  src/Pages/Search.jsx
  src/Pages/SingleView.js
Labels: code review

#383 [GRUPO 28] - Requisito 6
  src/components/CategoryList.js
  src/components/ProductList.js
  src/services/api.js
Labels: code review

#395 Group 35 - feat(Cart): Adiciona requisitos 8 e 9
  src/App.js
  src/components/AddToCartButton.js
  src/components/CartItem.css
  src/components/CartItem.js
  src/components/ProductCard.js
  src/components/SearchResults.js
  src/pages/CartShop.css
  src/pages/CartShop.jsx
  src/pages/ProductDetails.css
  src/pages/ProductDetails.js
  src/services/cart.js
Labels: code review

#289 [GRUPO 27] Criar listagem de produtos
  src/components/CardProduct.js
  src/components/Header.js
  src/components/Main.js
  src/pages/Home.js
Labels: code review

#419 [Group-20][Req-5][Req-6]
  src/App.css
  src/App.js
  src/components/AsideMenu.js
  src/components/ProductCard.js
  src/components/ProductList.js
  src/components/SearchBar.js
  src/pages/Home.js
  src/pages/home.js
  src/services/api.js
  src/styles/components/AsideMenu.css
  src/styles/components/ProductCard.css
  src/styles/components/ProductList.css
  src/styles/components/SearchBar.css
  src/styles/pages/Home.css
  src/styles/pages/ShoppingCart.css
Labels: code review

#456 [Grupo 28] - Requisito 07
  src/App.css
  src/App.js
  src/components/ProductDetails.js
  src/components/ProductItem.js
  src/components/ProductList.js
Labels: code review

#478 Main group 33 add to cart from details
  src/components/AddToCartButton.js
  src/components/CartButton.js
  src/components/CategoriesList.js
  src/components/ProductCard.js
  src/components/SearchBar.js
  src/pages/ProductDetails.js
  src/pages/ProductList.js
  src/pages/ShoppingCart.js
Labels: code review

#467 [Grupo29] Requisito 11
  src/components/ProductDetails.jsx
Labels: code review

#442 [GROUP 5][FEAT][DETAILED PRODUCT DISPLAY]
  public/logo_arrow_back.svg
  src/App.js
  src/components/ProductCard.js
  src/components/ProductDetailed.js
  src/services/api.js
Labels: developing

#496 requirement 10
  src/pages/Cart.js
  src/pages/Home.js
  src/pages/ProductDetails.js
  src/styles/Cart.css
Labels: code review

#511 [FIX][Product Details][Requisito 7]
  src/App.js
  src/Components/ItemCard.js
  src/Components/ProductDetails.js
  src/Components/SearchField.js
Labels: code review

#508 [Grupo 4] - Feat/ Estilo da página shopping cart
  src/components/ProductCart.js
  src/components/ShoppingCart.js
  src/styles/Checkout.css
  src/styles/ProductCart.css
  src/styles/ShoppingCart.css
Labels: code review

#522 [Group-20][Req-10]
  src/App.js
  src/components/CartItem.js
  src/components/ProductCard.js
  src/components/ProductDetails.js
  src/pages/ShoppingCart.js
  src/styles/components/CartItem.css
  src/styles/components/ProductCard.css
  src/styles/pages/ShoppingCart.css
Labels: code review

#497 [GRUPO 27] Cria botão de adicionar produto ao carrinho
  src/components/AddProductToCartButton.js
  src/components/CardProduct.js
  src/services/cart.js
Labels: code review

#525 [Group20] [Req09]
  package-lock.json
  package.json
  src/App.js
  src/__tests__/requirement11.test.js
  src/components/ProductCard.js
  src/components/ProductDetails.js
  src/components/ProductEvaluation.js
  src/components/RatingEvaluation.js
  src/styles/components/ProductCard.css
  src/styles/components/ProductDetails.css
Labels: code review

#531 [No Master, No Store][requisito 10 e 14]
  src/components/Card.js
  src/components/CardReview.js
  src/pages/Cart.js
  src/pages/LandingPage.js
  src/pages/ProductDetais.js
Labels: code review

#533 Main group 3 requisito 10
  README.md
  package-lock.json
  src/App.css
  src/App.js
  src/components/Cart.jsx
  src/components/CartItem.jsx
  src/components/Categories.jsx
  src/components/ProductCard.jsx
  src/components/ProductDetail.jsx
  src/components/ProductList.jsx
  src/components/SearchProduct.jsx
  src/css/productList.css
  src/services/api.js
Labels: code review

#543 ajuste referente ao conflito na branch do requisito 08
  src/App.css
  src/components/ProductItem.jsx
  src/components/ProductList.js
  src/components/ShoppingCartItens.jsx
  src/pages/InitialPage.js
  src/pages/ShoppingCart.js
Labels: code review

#526 Group 35 - feat(CartIcon): Adiciona requisito 13
  src/App.js
  src/components/AbstractCartHandler.js
  src/components/AddToCartButton.js
  src/components/CartIcon.jsx
  src/components/SearchResults.js
  src/pages/CartShop.jsx
  src/pages/ProductDetails.js
  src/pages/ProductList.js
  src/services/cart.js
  src/services/objects.js
Labels: code review

#546 [FIX][Add to cart detail][Requisito 9]
  src/Components/AddToCartDetail.js
  src/Components/EvaluateProduct.js
  src/Components/ProductDetails.js
Labels: code review

#548 [Grupo 28] Requisito 08
  src/App.js
  src/components/CartButton.js
  src/components/CartList.js
  src/components/ProductItem.js
Labels: code review

#552 [Grupo 28] - Requisito 09
  src/components/ProductDetails.js
Labels: code review

#523 [Grupo 28] - Requisito 11
  src/App.css
  src/components/ProductDetails.js
Labels: code review

#440 [FEAT 11,12] Grupo 24
  package-lock.json
  package.json
  src/App.js
  src/components/Carrinho.js
  src/components/Checkout.jsx
  src/components/Detalhes.jsx
  src/components/Home.js
  src/components/ItemsCart.jsx
  src/components/ProductRating.jsx
  src/components/SearchCard.jsx
Labels: code review

#547 realizado requisito 09
  src/components/ButtonAdd.jsx
  src/components/ProductItem.jsx
  src/components/ProductList.js
  src/pages/ProductDetails.js
Labels: code review

#573 Main group 24 feat 14 15
  src/components/Checkout.jsx
  src/components/Detalhes.jsx
  src/components/ItemsCart.jsx
  src/components/SearchCard.jsx
Labels: code review

#553 [Group-20][Req-12]
  public/images/icons8--cartão-de-credito.png
  public/images/icons8-código-de-barras-100.png
  src/App.js
  src/components/BuyerInputs.js
  src/components/CheckoutItem.js
  src/components/PaymentInputs.js
  src/components/ProductCard.js
  src/pages/Checkout.js
  src/pages/ShoppingCart.js
  src/styles/components/BuyerInputs.css
  src/styles/components/CartItem.css
  src/styles/components/CheckoutItem.css
  src/styles/components/PaymentInputs.css
  src/styles/components/ProductCard.css
  src/styles/components/SearchBar.css
  src/styles/pages/Checkout.css
  src/styles/pages/ShoppingCart.css
Labels: code review

#579 [Group-20][Req-Bonus]
  src/App.js
  src/components/CartIcon.js
  src/components/CartItem.js
  src/components/ProductCard.js
  src/components/ProductDetails.js
  src/components/RatingEvaluation.js
  src/components/SearchBar.js
  src/pages/Home.js
  src/pages/ShoppingCart.js
  src/styles/components/CartIcon.css
  src/styles/components/ProductCard.css
  src/styles/components/ProductDetails.css
  src/styles/components/SearchBar.css
Labels: code review

#563 [GRUPO6][REQUISITO7] - Redirecione para uma tela com a exibição detalhada ao clicar na exibição resumida de um produto
  src/components/ShowDetailsButton.js
  src/pages/MainContent.js
  src/pages/ProductDetails.js
Labels: Em desenvolvimento

#514 Feature evaluation
  src/pages/ProductDetails.js
  src/styles/ProductDetails.css
Labels: code review
